name = "rae"
compatibility_date = "2026-06-06"
main = "src/index.js"

[assets]
directory = "."
binding = "ASSETS"
run_worker_first = [ "/*.md", "/docs/*.md", "/presentations/*.md" ]

[[d1_databases]]
binding = "DB"
database_name = "rae-slides"
database_id = "6ba4a2e4-5155-44c2-b3fc-27fbe6096704"
