// AUTO-GENERATED by seed.js from site-data.js — do not edit by hand.
// Lists the slugs and source file paths of items marked `public: true`.
// The Worker uses this to (a) allow the public read API only for public slugs
// and (b) allow direct .md fetches only for public source files.
export const PUBLIC_SLUGS = [
  "cosmos-spatializing-community",
  "experience",
  "cardinal-agentic-spending",
  "social-lab-climate-goal-platform",
  "gtr-partners",
  "cloudflare-case-study",
  "cosmos-research-report",
  "cosmos-research-deck",
  "social-lab-climate-goal-report",
  "social-lab-prd-stage1",
  "social-lab-prd-stage2",
  "slide-guide",
  "implementation-plan",
  "readme"
];

// Repo-root-relative paths of public .md sources.
export const PUBLIC_FILES = [
  "presentations/cosmos-spatializing-asynchronous-community-jun11.md",
  "presentations/experience-cosmos-research-plan.md",
  "presentations/cardinal-agentic-workplace-spending.md",
  "presentations/social-lab-climate-goal-platform.md",
  "presentations/gtr-startups-climate-awareness.md",
  "presentations/cloudflare-case-study.md",
  "docs/cosmos-research-report-jun11.md",
  "docs/social-lab-climate-goal-platform-report-jun15.md",
  "docs/prd-stage1-climate-impact-dashboard.md",
  "docs/prd-stage2-generalization-customization.md",
  "SLIDE_GUIDE.md",
  "IMPLEMENTATION_PLAN.md",
  "README.md"
];
